name: linux-vnc

on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: install ubuntu-desktop 
      run: |
        # sudo apt update
        # sudo apt upgrade
        sudo apt install ubuntu-desktop 
    - name: install vnc
      run: |
        sudo apt install dbus-x11
        sudo apt install tigervnc-standalone-server tigervnc-common
        mkdir -p $HOME/.vnc
        echo "123456" | vncpasswd -f > $HOME/.vnc/passwd
        sudo chmod 600 $HOME/.vnc/passwd
        set +H
        echo -e "#!/bin/sh\nunset SESSION_MANAGER\nunset DBUS_SESSION_BUS_ADDRESS\ngnome-session" >> ~/.vnc/xstartup
        set -H
        chmod +x ~/.vnc/xstartup
        vncserver -geometry 1920x1080 :1 -localhost no -depth 24 -rfbport 11451
    - name: install ngrok
      run: | 
        curl -sSL https://ngrok-agent.s3.amazonaws.com/ngrok.asc \
        | sudo tee /etc/apt/trusted.gpg.d/ngrok.asc >/dev/null \
        && echo "deb https://ngrok-agent.s3.amazonaws.com buster main" \
        | sudo tee /etc/apt/sources.list.d/ngrok.list \
        && sudo apt update \
        && sudo apt install ngrok
    - run: ngrok authtoken $NGROK_AUTH_TOKEN
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
    - run: ngrok tcp 11451
